import { Container } from "@mantine/core";
import axios from "axios";
import Head from "next/head";
import Features from "../components/Features";
import PizzaList from "../components/PizzaList";
import Product from "../models/Product";
import dbConnect from "../lib/dbConnect";

export default function Home({ products, error }) {
  console.log("products: ", products);
  if (error) return "Error";
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Features />
      <Container size='xl'>
        <PizzaList products={products} />
      </Container>
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    await dbConnect();
    const results = await Product.find();
    const products = await JSON.parse(JSON.stringify(results));
    return {
      props: {
        products,
      },
    };
  } catch (error) {
    return {
      props: {
        error,
      },
    };
  }
};
